export const URLS = {
  LINKEDIN: "https://www.linkedin.com/in/prince-yadav-0b3267382",
  GITHUB: "https://github.com/princeghostme",
  WHATSAPP: "https://wa.me/917004571707",
  PORTFOLIO: "https://princeghostme.github.io/portfolio/",
};

export const RESUME = {
  PDF: "https://prince-react-app-first.s3.eu-north-1.amazonaws.com/Prince_Yadav_CV.pdf",
  DOCX: "https://prince-react-app-first.s3.eu-north-1.amazonaws.com/Resume/Prince_Yadav_CV.docx",
};

export interface PageTheme {
  gradient: string;
  className: string;
  primaryColor: string;
  accentColor: string;
  bg50: string;
  bg100: string;
  bg200: string;
  text600: string;
  text700: string;
  text800: string;
  text900: string;
  border200: string;
  gradientFrom400To600: string;
}

export const PAGE_THEMES: Record<string, PageTheme> = {
  home: {
    gradient: "from-cyan-50 via-sky-50 to-blue-50",
    className: "theme-home",
    primaryColor: "sky",
    accentColor: "cyan",
    bg50: "bg-sky-50",
    bg100: "bg-sky-100",
    bg200: "bg-sky-200",
    text600: "text-sky-600",
    text700: "text-sky-700",
    text800: "text-sky-800",
    text900: "text-sky-900",
    border200: "border-sky-200",
    gradientFrom400To600: "from-sky-400 to-sky-600",
  },
  skills: {
    gradient: "from-emerald-50 via-teal-50 to-green-50",
    className: "theme-skills",
    primaryColor: "emerald",
    accentColor: "teal",
    bg50: "bg-emerald-50",
    bg100: "bg-emerald-100",
    bg200: "bg-emerald-200",
    text600: "text-emerald-600",
    text700: "text-emerald-700",
    text800: "text-emerald-800",
    text900: "text-emerald-900",
    border200: "border-emerald-200",
    gradientFrom400To600: "from-emerald-400 to-emerald-600",
  },
  projects: {
    gradient: "from-indigo-50 via-violet-50 to-purple-50",
    className: "theme-projects",
    primaryColor: "indigo",
    accentColor: "violet",
    bg50: "bg-indigo-50",
    bg100: "bg-indigo-100",
    bg200: "bg-indigo-200",
    text600: "text-indigo-600",
    text700: "text-indigo-700",
    text800: "text-indigo-800",
    text900: "text-indigo-900",
    border200: "border-indigo-200",
    gradientFrom400To600: "from-indigo-400 to-indigo-600",
  },
  work: {
    gradient: "from-orange-50 via-amber-50 to-yellow-50",
    className: "theme-work",
    primaryColor: "orange",
    accentColor: "amber",
    bg50: "bg-orange-50",
    bg100: "bg-orange-100",
    bg200: "bg-orange-200",
    text600: "text-orange-600",
    text700: "text-orange-700",
    text800: "text-orange-800",
    text900: "text-orange-900",
    border200: "border-orange-200",
    gradientFrom400To600: "from-orange-400 to-orange-600",
  },
  about: {
    gradient: "from-purple-50 via-fuchsia-50 to-pink-50",
    className: "theme-about",
    primaryColor: "purple",
    accentColor: "fuchsia",
    bg50: "bg-purple-50",
    bg100: "bg-purple-100",
    bg200: "bg-purple-200",
    text600: "text-purple-600",
    text700: "text-purple-700",
    text800: "text-purple-800",
    text900: "text-purple-900",
    border200: "border-purple-200",
    gradientFrom400To600: "from-purple-400 to-purple-600",
  },
};

export const RESUME_DATA = {
  personal: {
    name: "Prince Yadav",
    title: "Full Stack Developer | .NET Core, Angular, React",
    email: "yaduvanshiprince2007@gmail.com",
    phone: "+91 7004571707",
    location: "Bengaluru, Karnataka",
    summary:
      "Results-driven Full Stack Developer with 5 years of experience building secure, scalable, and cloud-native applications. Strong expertise in .NET Core, ASP.NET Web API, Node.js, React, and Next.js, with deep knowledge of SQL Server, PostgreSQL, MongoDB, Cosmos DB, and Redis. Experienced in designing microservices, building high-performance REST/gRPC APIs, and implementing CI/CD pipelines using Azure DevOps and GitHub Actions. Hands-on with Docker, Kubernetes, and cloud platforms including Azure and AWS. Focused on performance optimization, caching, rate limiting, and asynchronous processing. Proven track record of delivering high impact solutions in fintech, SaaS, and enterprise environments. Skilled in rapid prototyping and AI-assisted development using tools like GitHub Copilot and ChatGPT to accelerate development and improve code quality.",
  },
  experience: [
    {
      id: 1,
      startDate: "Nov 2025",
      endDate: "Present",
      company: "DynPro India",
      location: "Bengaluru, Karnataka",
      position: "Full Stack Developer",
      clients: ["Deloitte (USI)", "Takeda"],
      techStack: [
        ".NET Core",
        "C#",
        "Angular",
        "SQL Server",
        "MongoDB",
        "AWS",
        "REST APIs",
        "CI/CD (GitHub Actions)",
        "Redis",
      ],
      responsibilities: [
        "Developed and maintained enterprise web applications using .NET Core and Angular.",
        "Designed and developed REST APIs, enabling seamless integration with frontend modules and improving data flow efficiency.",
        "Implemented Redis caching to improve performance and reduce database load.",
        "Performed resiliency testing by simulating API failures and validating application stability.",
        "Resolved production issues and enhanced application performance.",
      ],
    },
    {
      id: 2,
      startDate: "Apr 2025",
      endDate: "Nov 2025",
      company: "Aaneel Infotech",
      location: "Bengaluru, Karnataka",
      position: "Full Stack Developer (Software Developer / Assistant Lead)",
      clients: ["Wellbe Health"],
      techStack: [
        ".NET Core",
        "C#",
        "React.js",
        "Azure",
        "SQL Server",
        "PostgreSQL",
        "REST API",
        "HTML/CSS",
        "CI/CD (Azure DevOps)",
        "PWA",
      ],
      responsibilities: [
        "Led backend and frontend development for healthcare clients to deliver secure and scalable cloud-based applications.",
        "Designed and optimized REST APIs in .NET Core and Express.js, ensuring high availability and 30% faster data throughput.",
        "Built and integrated a Progressive Web App (PWA) into React, enabling cross-platform accessibility and offline sync.",
        "Implemented IMO search, version master control, and CDN-based delta updates for content optimization.",
        "Mentored junior developers and conducted code reviews to maintain best practices and architectural standards.",
      ],
    },
    {
      id: 3,
      startDate: "Dec 2023",
      endDate: "Mar 2025",
      company: "MITS Global",
      location: "Bengaluru, Karnataka",
      position: "Full Stack Developer (Software Developer / Assistant Lead)",
      clients: ["Nuvama (FinTech)"],
      techStack: [
        ".NET Core",
        "C#",
        "React.js",
        "AWS (EC2, Amplify, S3, Lambda)",
        "SQL Server",
        "REST APIs",
        "HTML/CSS",
        "Git",
        "CI/CD Pipelines",
      ],
      responsibilities: [
        "Collaborated with Nuvama (FinTech) to design, develop, and deploy enterprise-grade financial applications.",
        "Engineered high-performance APIs in .NET Core, reducing response latency by 30%.",
        "Developed interactive React dashboards integrated with AWS-hosted services.",
        "Utilized AWS Lambda and S3 for event-driven data handling and secure file management.",
        "Built Python-based analytics dashboards to extract insights from system and user metrics.",
        "Enhanced authentication, API wrappers, and login modules for higher security and performance.",
        "Managed production deployments with zero downtime, overseeing release readiness and hotfixes.",
        "Acted as team lead proxy, handling sprint planning, stakeholder communication, and requirement analysis.",
      ],
    },
    {
      id: 4,
      startDate: "Feb 2022",
      endDate: "Dec 2023",
      company: "Enaviya Information Technologies",
      location: "Bengaluru, Karnataka",
      position: "Software Developer",
      clients: ["SIS", "AU Bank", "Ashirwad"],
      techStack: [
        ".NET Core MVC",
        "C#",
        "Angular",
        "AWS",
        "Azure",
        "SQL Server",
        "PostgreSQL",
        "REST APIs",
        "SharePoint",
        "HTML/CSS",
      ],
      responsibilities: [
        "Delivered end-to-end enterprise applications using .NET Core API, Angular, and SQL/PostgreSQL.",
        "Designed reusable service APIs and modular components, improving maintainability and scalability.",
        "Partnered with SIS and AU Bank to implement secure authentication and financial workflows.",
        "Developed and maintained SharePoint solutions (workflows, CAML queries, timer jobs) for Ashirwad.",
      ],
    },
    {
      id: 5,
      startDate: "Aug 2021",
      endDate: "Dec 2021",
      company: "Add Innovation",
      location: "Greater Noida, UP",
      position: "Full Stack Developer (Trainee / Junior Developer)",
      clients: [],
      techStack: [
        "C#",
        ".NET Framework",
        "Python",
        "PostgreSQL",
        "WinForms",
        "HTML/CSS",
        "Data Analytics",
      ],
      responsibilities: [
        "Contributed to an AI/ML-driven image processing system for automated quality inspection.",
        "Built UI interfaces and integrated data workflows using PostgreSQL and Windows Forms.",
        "Developed Python-based analytics dashboards to monitor performance and usage trends.",
        "Collaborated with cross-functional hardware/software teams to enhance reliability and achieve a 25% faster inspection cycle.",
      ],
    },
  ],
  internships: [
    {
      id: 1,
      startDate: "Feb 2021",
      endDate: "Jul 2021",
      company: "Hindalco",
      location: "Renukoot, UP",
      position: "IT Trainee",
      responsibilities: [
        "Supported development of an updated Employee Management System, enhancing operational efficiency.",
        "Delivered system migration 6 months ahead of schedule by aligning closely with IT and HR stakeholders.",
        "Conducted requirement analysis, system integration, and user training to ensure smooth adoption.",
      ],
    },
    {
      id: 2,
      startDate: "Aug 2020",
      endDate: "Dec 2020",
      company: "Lithoera Technology",
      location: "Bengaluru, Karnataka",
      position: "Full Stack Intern (Team Lead)",
      responsibilities: [
        "Led a 4-member team for an IoT-based government project, delivering innovative solutions.",
        "Enhanced backend services using Python and REST APIs, ensuring smooth IoT-device integration.",
        "Published research in IJSRD, Vol-8 Issue 10, Dec-2020, highlighting system architecture and results.",
      ],
    },
    {
      id: 3,
      startDate: "Feb 2018",
      endDate: "Dec 2019",
      company: "PIALGO Solutions",
      location: "Ranchi, Jharkhand",
      position: "UI/UX Frontend Trainee",
      responsibilities: [
        "Delivered UI modules for enterprise projects with focus on usability, accessibility, and responsiveness.",
        "Collaborated with designers and developers to translate mockups into interactive components.",
        "Built reusable frontend components with HTML, CSS, and JavaScript, Angular and React.",
      ],
    },
  ],
  skills: {
    programmingLanguages: [
      "C#",
      "JavaScript (ES6+)",
      "TypeScript",
      "Node.js",
      "Python",
      "SQL",
      "NoSQL",
      "C/C++",
      "Shell Scripting",
    ],
    coreConcepts: [
      "LINQ",
      "Multithreading",
      "Async Programming",
      "DSA",
      "OOP",
    ],
    frontend: [
      "Angular",
      "React.js",
      "Next.js",
      "Redux",
      "Context API",
      "Tailwind CSS",
      "Bootstrap",
      "Material UI",
      "SCSS",
      "PWA",
      "SEO Optimization",
      "Accessibility (WCAG)",
    ],
    backend: [
      "ASP.NET",
      "ASP.NET Core",
      "Web API",
      "Entity Framework Core",
      "SignalR",
      "Node.js",
      "Express.js",
      "Microservices Architecture",
      "CQRS",
    ],
    apis: [
      "REST APIs",
      "gRPC",
      "GraphQL",
      "WebSocket",
      "OAuth2",
      "JWT",
      "Certificate-based Authentication",
      "OKTA",
    ],
    databases: [
      "SQL Server",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Cosmos DB",
      "DynamoDB",
      "Redis",
      "ClickHouse",
    ],
    cloudDevOps: [
      "Azure (App Services, Functions, Blob Storage, DevOps)",
      "AWS (EC2, S3, Lambda, RDS)",
      "Docker",
      "Kubernetes",
      "CI/CD: GitHub Actions, Azure DevOps, Jenkins",
    ],
    performance: [
      "Caching (Redis, CDN)",
      "Rate Limiting",
      "Load Balancing",
      "Pagination",
      "Sharding",
      "Compression",
      "Asynchronous Processing",
      "Queues (Kafka, RabbitMQ, SQS)",
    ],
    tools: [
      "Git",
      "GitHub",
      "GitLab",
      "Bitbucket",
      "JIRA",
      "Confluence",
      "Agile/Scrum",
      "Postman",
      "Swagger",
      "Chrome DevTools",
    ],
    aiAutomation: [
      "AI-assisted development: GitHub Copilot, ChatGPT",
      "Additional exposure: Gemini, Claude, DeepSeek, Cursor, Trae, Mistral AI",
      "Use cases: AI search, chatbots, document summarization, generative APIs",
    ],
  },
  education: [
    {
      id: 1,
      startDate: "Aug 2019",
      endDate: "May 2021",
      degree: "Master of Computer Application (MCA)",
      university: "Reva University, Bangalore",
      gpa: "8.2 GPA",
      description:
        "Focused on advanced programming, software development methodologies, and optimization techniques.",
    },
    {
      id: 2,
      startDate: "Jun 2016",
      endDate: "May 2019",
      degree: "Bachelor of Computer Application (BCA)",
      university: "ICFAI University, Bangalore",
      gpa: "7.3 GPA",
      description:
        "Gained solid foundation in programming, algorithms, and database management.",
    },
    {
      id: 3,
      startDate: "Apr 2015",
      endDate: "Mar 2016",
      degree: "Higher Secondary Education (Physics, Chemistry, Mathematics)",
      university: "Army Public School, CBSE Board",
      gpa: "7 CGPA",
      description:
        "Completed higher secondary education with strong analytical and problem-solving skills.",
    },
    {
      id: 4,
      startDate: "Apr 2012",
      endDate: "Mar 2013",
      degree: "Middle School Education",
      university: "Army Public School, CBSE Board",
      gpa: "7.2 CGPA",
      description:
        "Completed middle school with a broad curriculum, laying groundwork for future studies.",
    },
  ],
  certifications: [
    "Full Stack Web Development – Udemy",
    "ASP.NET Core React Advanced – Udemy",
    "Python for Data Science AI – Udemy",
    "CI/CD with Azure DevOps – Udemy",
    "Microsoft Azure Fundamentals – Udemy",
    "Generative AI with .NET – Udemy",
  ],
  languages: ["English", "Hindi"],
};